### PR TITLE
new wcrp function updates

### PR DESCRIPTION
**Pull request by TomasMillaKoch**

### CODE REVIEW

**Review by smnorris — COMMENTED** [review]
`wcrp_barrier_count.sql` fails to complete:
```
$ psql $DATABASE_URL -f sql/functions/wcrp_barrier_count.sql
DROP FUNCTION
psql:sql/functions/wcrp_barrier_count.sql:229: ERROR:  syntax error at end of input
LINE 226: $$;
```

**Comment by smnorris** [comment]
The other updates seem fine, I am not sure what is causing the error in the count query, probably something minor.

**Comment by TomasMillaKoch** [comment]
Ok I have changed the else if syntax so maybe this is the error because I cannot see anything  else right away.

**Comment by smnorris** [comment]
That did it, thanks.

**Pull request merged**
